### ISSUE TITLE
Error while decoding data: chunk overflow at 32818 cells when opening place

### ISSUE THREAD

**Issue by pro11x11** [Roblox-Devs/magnus-night-v3#1]
when i open the saved place it say 
![image](https://github.com/Roblox-Devs/magnus-night-v3/assets/110092289/c7aad454-34f0-4a75-9d98-613d9e151044)
logs are 

> save reoijregij
giant size @1b768fc6640, size 10739
aka 18410996206198128512
80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff800588019508880180098802
giant size resized
giant size done
giant size @1b7af0bb160, size 10536
aka 18410996206198128512
80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff80ff8001080e028e019506880185
giant size resized
giant size done
save finished in 10169359700 ns
saving to reoijregij.rbxlx
saved
how to fix

**Comment by devnorb** [comment]
same issue

**Comment by stan2474** [comment]
send game link

**Comment by pro11x11** [comment]
https://www.roblox.com/games/6678877691/ZO-SAMURAI-SWORD-FIGHTING

**Comment by Subashians** [comment]
french

**Comment by stan2474** [comment]
``chunk overflow at x cells`` is an issue that will currently not be fixed due to how ROBLOX handles terrain (terrain changes all the time which is why this error is caused), i suggest you don't save terrain
