### ISSUE TITLE
man what does this mean?

### ISSUE THREAD

**Issue by nexkoa** [Roblox-Devs/magnus-night-v3#5]
![image](https://github.com/Roblox-Devs/magnus-night-v3/assets/141091507/7a4c2bad-2b08-4ea0-968e-257e5e68f8bf)
is the decompile script still broken or what is this?

**Comment by stan2474** [comment]
that is bytecode, it is there intentionally for advanced users who need it/want it.

**Comment by nexkoa** [comment]
> that is bytecode, it is there intentionally for advanced users who need it/want it.

is the decompiler local still getting working on?

**Comment by nexkoa** [comment]
![image](https://github.com/Roblox-Devs/magnus-night-v3/assets/141091507/d87bdc89-32b4-49c8-b2d9-d8a8809c22de)
because what is this
