### ISSUE TITLE
Output Location

### ISSUE THREAD

**Issue by Luc69lol** [Roblox-Devs/magnus-night-v3#6]
This worked well with a little bit of trial. But when I finally saved the rbxlx I don't know where it output to.

**Comment by Luc69lol** [comment]
![Screenshot 2024-01-09 070417](https://github.com/Roblox-Devs/magnus-night-v3/assets/120069015/90569a53-797e-44a2-bce0-c767f6bf90c0)

**Comment by stan2474** [comment]
it should output to where the exe is located

**Comment by Luc69lol** [comment]
yeah this worked thanks
